### ISSUE TITLE
Тіпа чат

### ISSUE THREAD

**Issue by pavelzabiyaka** [povstenko/quiztable#1]
Додай _мене_ до проекту, **собака**.
Дякую.

**Comment by pavelzabiyaka** [comment]
Проект має потенціал. Хочу бути контрібутором.

**Comment by pavelzabiyaka** [comment]
![default](https://user-images.githubusercontent.com/48098729/53587900-3dd3cc80-3b94-11e9-9ff4-e241d7f57fc6.png)

**Comment by pavelzabiyaka** [comment]
http://www.chem-mind.com/%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B_%D0%BC%D0%B5%D0%BD%D0%B4%D0%B5%D0%BB%D0%B5%D0%B5%D0%B2%D0%B0/

**Comment by povstenko** [comment]
Переконав. тепер ти соавтор мого репозiторiя.

**Comment by pavelzabiyaka** [comment]
Чудово!

**Comment by pavelzabiyaka** [comment]
![image](https://user-images.githubusercontent.com/48098729/53638721-cb182f00-3c2f-11e9-94fa-6d39088ab79b.png)

**Comment by pavelzabiyaka** [comment]
![image](https://user-images.githubusercontent.com/48098729/53638745-eb47ee00-3c2f-11e9-9f6d-2d5e7d0fe015.png)
 Смоктати!!

**Comment by povstenko** [comment]
Будь-ласка, ведіть себе пристойно i пишіть по темі проекту.

**Comment by povstenko** [comment]
![image](https://user-images.githubusercontent.com/45174840/53639002-abcdd180-3c30-11e9-870f-587a408e9ab6.png)
